---
- include_tasks:        '../tasks/install_packages.yml'
- include_tasks:        '../tasks/system_groups.yml'
- include_tasks:        '../tasks/system_users.yml'
- include_tasks:        '../tasks/sync_dirs.yml'
- include_tasks:        '../tasks/install_files.yml'
- include_tasks:        '../tasks/template_files.yml'
- include_tasks:        '../tasks/symlinks.yml'
- include_tasks:        '../tasks/shell_commands.yml'
- include_tasks:        '../tasks/restart_services.yml'
  when:                 template_files_result.changed
                        or symlinks_result.changed
